# Netlify deployment configuration.
# See: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
# Root directory of the output is _site/.
publish = "_site/"

[build.processing]
# We already optimize assets at build time, so Netlify can't do much more here.
# When Netlify optimizes, it hosts them at a different URL, which causes
# problems with CSP. It's just easier to disable Netlify's optimizations and use
# the real resources generated.
skip_processing = true

[[redirects]]
# Serve the 404 page at any unhandled URLs. This technically isn't a redirect,
# it just serves a status code 404 with the contents of the `to` location.
# See: https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling
from = "*"
to = "/404/"
status = 404
